language: python
python:
  - "3.6"
dist: trusty
sudo: false

services:
  - postgresql

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libpq-dev

install:
  - make install-dev
#  - npm install
#  - npm run build

before_script:
  - make bootstrap-db

script:
  - make lint
  - make test

after_success:
  - coveralls
