version: '3'
services:
  jarr-server:
    build:
      dockerfile: containers/server/Dockerfile
      context: .
    ports:
      - 8000:8000
    networks:
      - frontend
      - backend
    depends_on:
      - redis
      - postgresql
      - rabbitmq
  crawler:
    build:
      dockerfile: containers/crawler/Dockerfile
      context: .
    networks:
      - backend
    depends_on:
      - jarr-server
  redis:
    image: redis
    ports:
      - 6379
  rabbitmq:
    image: rabbitmq
    ports:
      - "25672"
      - "4369"
      - "5671"
      - "5672"
  postgresql:
    image: postgres:11
    volumes:
      - ./jarr-data:/var/lib/postgresql/data
